apiVersion: apps/v1
kind: Deployment
metadata:
  name: cas-dashboard
spec:
  selector:
    matchLabels:
      app: cas-dashboard
  replicas: 3
  template:
    metadata:
      labels:
        app: cas-dashboard
    spec:
     containers:
     - name: cas-dashboard
       image: hoandm/cas_dashboard
       ports:
       - containerPort: 8080


---


apiVersion: v1
kind: Service
metadata:
  name: cas-dashboard
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30001
  selector:
    app: cas-dashboard


